name: example_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: '^0.1.0'
  cached_network_image: '^0.4.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
